# Generated by Django 3.0.7 on 2020-06-23 04:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RushingPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('team', models.CharField('team', max_length=3)),
                ('position',models.CharField('pos', max_length=2)),
                ('att', models.DecimalField(
                    'att', max_digits=3, decimal_places=2)),
                ('att_g', models.DecimalField(
                    'att_g', max_digits=3, decimal_places=2)),
                ('yds', models.DecimalField(
                    'yds', max_digits=3, decimal_places=2)),
                ('avg', models.DecimalField(
                    'avg', max_digits=4, decimal_places=2)),
                ('yds_g', models.DecimalField(
                    'yds_g', max_digits=3, decimal_places=2)),
                ('td', models.DecimalField(
                    'td', max_digits=2, decimal_places=2)),
                ('lng', models.DecimalField(
                    'lng', max_digits=2, decimal_places=2)),
                ('first', models.DecimalField(
                    'first', max_digits=2, decimal_places=2)),
                ('first_percent', models.DecimalField(
                    'first_percent', max_digits=3, decimal_places=2)),
                ('twenty_plus', models.DecimalField(
                    'twenty_plus', max_digits=2, decimal_places=2)),
                ('forty_plus', models.DecimalField(
                    'forty_plus', max_digits=2, decimal_places=2)),
                ('fum', models.DecimalField(
                    'fum', max_digits=2, decimal_places=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
